# Generated by Django 4.2.2 on 2023-06-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PokeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poke_name", models.CharField(max_length=50)),
                ("poke_image", models.ImageField(upload_to="")),
                ("poke_number", models.IntegerField()),
                ("poke_type", models.CharField(blank=True, max_length=30, null=True)),
                ("poke_type2", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "poke_ability",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "poke_ability2",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "poke_abi_hidden",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("poke_hp", models.IntegerField()),
                ("poke_attack", models.IntegerField()),
                ("poke_defense", models.IntegerField()),
                ("poke_sp_atk", models.IntegerField()),
                ("poke_sp_def", models.IntegerField()),
                ("poke_speed", models.IntegerField()),
                ("poke_base_stats", models.IntegerField()),
            ],
        ),
    ]
