# Generated by Django 4.2.2 on 2023-06-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokedmgapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PokeMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pokemodel",
            name="before_evolution",
            field=models.BooleanField(default=True, help_text="進化前ならTrue"),
        ),
        migrations.AlterField(
            model_name="pokemodel",
            name="poke_attack",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pokemodel",
            name="poke_base_stats",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pokemodel",
            name="poke_defense",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pokemodel",
            name="poke_hp",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pokemodel",
            name="poke_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="pokemodel",
            name="poke_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pokemodel",
            name="poke_sp_atk",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pokemodel",
            name="poke_sp_def",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pokemodel",
            name="poke_speed",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
