# Generated by Django 4.2.2 on 2023-07-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokedmgapp", "0002_pokemove_pokemodel_before_evolution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemove",
            name="move_PP",
            field=models.IntegerField(blank=True, help_text="技の使用可能回数", null=True),
        ),
        migrations.AddField(
            model_name="pokemove",
            name="move_accuracy",
            field=models.IntegerField(blank=True, help_text="命中率", null=True),
        ),
        migrations.AddField(
            model_name="pokemove",
            name="move_class",
            field=models.CharField(
                blank=True,
                choices=[("physical", "物理技"), ("special", "特殊技"), ("status", "変化技")],
                default="physical",
                help_text="技の分類",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pokemove",
            name="move_defend",
            field=models.BooleanField(
                blank=True, default=True, help_text="守れるならcheck", null=True
            ),
        ),
        migrations.AddField(
            model_name="pokemove",
            name="move_direct",
            field=models.BooleanField(
                blank=True, default=True, help_text="直接ならcheck", null=True
            ),
        ),
        migrations.AddField(
            model_name="pokemove",
            name="move_effect",
            field=models.TextField(blank=True, help_text="技の説明", null=True),
        ),
        migrations.AddField(
            model_name="pokemove",
            name="move_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="pokemove",
            name="move_power",
            field=models.IntegerField(blank=True, help_text="技の威力", null=True),
        ),
        migrations.AddField(
            model_name="pokemove",
            name="move_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "なし"),
                    ("normal", "ノーマル"),
                    ("fire", "ほのお"),
                    ("water", "みず"),
                    ("electric", "でんき"),
                    ("grass", "くさ"),
                    ("ice", "こおり"),
                    ("fighting", "かくとう"),
                    ("poison", "どく"),
                    ("ground", "じめん"),
                    ("flying", "ひこう"),
                    ("psychic", "エスパー"),
                    ("bug", "むし"),
                    ("rock", "いわ"),
                    ("ghost", "ゴースト"),
                    ("dragon", "ドラゴン"),
                    ("dark", "あく"),
                    ("steel", "はがね"),
                    ("fairy", "フェアリー"),
                ],
                default="none",
                max_length=10,
                null=True,
            ),
        ),
    ]
