# Generated by Django 4.2.2 on 2023-07-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokedmgapp", "0004_alter_pokemodel_poke_type_alter_pokemodel_poke_type2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemodel",
            name="poke_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("なし", "なし"),
                    ("ノーマル", "ノーマル"),
                    ("ほのお", "ほのお"),
                    ("みず", "みず"),
                    ("でんき", "でんき"),
                    ("くさ", "くさ"),
                    ("こおり", "こおり"),
                    ("かくとう", "かくとう"),
                    ("どく", "どく"),
                    ("じめん", "じめん"),
                    ("ひこう", "ひこう"),
                    ("エスパー", "エスパー"),
                    ("むし", "むし"),
                    ("いわ", "いわ"),
                    ("ゴースト", "ゴースト"),
                    ("ドラゴン", "ドラゴン"),
                    ("あく", "あく"),
                    ("はがね", "はがね"),
                    ("フェアリー", "フェアリー"),
                ],
                default="なし",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pokemodel",
            name="poke_type2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("なし", "なし"),
                    ("ノーマル", "ノーマル"),
                    ("ほのお", "ほのお"),
                    ("みず", "みず"),
                    ("でんき", "でんき"),
                    ("くさ", "くさ"),
                    ("こおり", "こおり"),
                    ("かくとう", "かくとう"),
                    ("どく", "どく"),
                    ("じめん", "じめん"),
                    ("ひこう", "ひこう"),
                    ("エスパー", "エスパー"),
                    ("むし", "むし"),
                    ("いわ", "いわ"),
                    ("ゴースト", "ゴースト"),
                    ("ドラゴン", "ドラゴン"),
                    ("あく", "あく"),
                    ("はがね", "はがね"),
                    ("フェアリー", "フェアリー"),
                ],
                default="なし",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pokemove",
            name="move_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("なし", "なし"),
                    ("ノーマル", "ノーマル"),
                    ("ほのお", "ほのお"),
                    ("みず", "みず"),
                    ("でんき", "でんき"),
                    ("くさ", "くさ"),
                    ("こおり", "こおり"),
                    ("かくとう", "かくとう"),
                    ("どく", "どく"),
                    ("じめん", "じめん"),
                    ("ひこう", "ひこう"),
                    ("エスパー", "エスパー"),
                    ("むし", "むし"),
                    ("いわ", "いわ"),
                    ("ゴースト", "ゴースト"),
                    ("ドラゴン", "ドラゴン"),
                    ("あく", "あく"),
                    ("はがね", "はがね"),
                    ("フェアリー", "フェアリー"),
                ],
                default="なし",
                max_length=10,
                null=True,
            ),
        ),
    ]
